import matplotlib.pyplot as plt
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
from statsmodels.tsa.stattools import acf, pacf

from utils.stats import get_acf_pacf_values
from utils.loader import load_data_ts_w1
from utils.viz import plot_time_series

v_ts_w1 = load_data_ts_w1()

type(v_ts_w1)

## Visualization of time series
plot_time_series(v_ts_w1, title='ts_w1')

# - The data consists of 45 daily observations of consecutive days between November 4 to January 10.
# - The figure suggests a **stationary process** with constant mean and variance.
# - The sample ACF decays exponentially and the sample PACF has a single significant spike at lag 1, indicating that time series **is likely** to be generated by a AR(1) process.